enum CAR_SLOT_ID {
	CARSLOTID_INVALID = -1,
	CARSLOTID_BADGING_BUMPER_SET_FRONT = 0x0,
	CARSLOTID_BADGING_BUMPER_SET_REAR = 0x1,
	CARSLOTID_BADGING_FENDER_FRONT_LEFT = 0x2,
	CARSLOTID_BADGING_FENDER_FRONT_RIGHT = 0x3,
	CARSLOTID_BADGING_FENDER_REAR_LEFT = 0x4,
	CARSLOTID_BADGING_FENDER_REAR_RIGHT = 0x5,
	CARSLOTID_BADGING_TRUNK = 0x6,
	CARSLOTID_BASE = 0x7,
	CARSLOTID_BODY = 0x8,
	CARSLOTID_BODY_DOORLINE = 0x9,
	CARSLOTID_BRAKE_CALIPER_FRONT = 0xA,
	CARSLOTID_BRAKE_CALIPER_REAR = 0xB,
	CARSLOTID_BRAKE_ROTOR_FRONT = 0xC,
	CARSLOTID_BRAKE_ROTOR_REAR = 0xD,
	CARSLOTID_BRAKELIGHT_GLASS_LEFT = 0xE,
	CARSLOTID_BRAKELIGHT_GLASS_RIGHT = 0xF,
	CARSLOTID_BRAKELIGHT_LEFT = 0x10,
	CARSLOTID_BRAKELIGHT_RIGHT = 0x11,
	CARSLOTID_BUMPER_FRONT = 0x12,
	CARSLOTID_BUMPER_FRONT_EXTRA = 0x13,
	CARSLOTID_BUMPER_REAR = 0x14,
	CARSLOTID_BUMPER_REAR_EXTRA = 0x15,
	CARSLOTID_DAMAGE_BODY = 0x16,
	CARSLOTID_DAMAGE_BRAKELIGHT_LEFT = 0x17,
	CARSLOTID_DAMAGE_BRAKELIGHT_RIGHT = 0x18,
	CARSLOTID_DAMAGE_BUMPER_FRONT = 0x19,
	CARSLOTID_DAMAGE_BUMPER_REAR = 0x1A,
	CARSLOTID_DAMAGE_DOOR_LEFT = 0x1B,
	CARSLOTID_DAMAGE_DOOR_REAR_LEFT = 0x1C,
	CARSLOTID_DAMAGE_DOOR_REAR_RIGHT = 0x1D,
	CARSLOTID_DAMAGE_DOOR_RIGHT = 0x1E,
	CARSLOTID_DAMAGE_FENDER_FRONT_LEFT = 0x1F,
	CARSLOTID_DAMAGE_FENDER_FRONT_RIGHT = 0x20,
	CARSLOTID_DAMAGE_HEADLIGHT_LEFT = 0x21,
	CARSLOTID_DAMAGE_HEADLIGHT_RIGHT = 0x22,
	CARSLOTID_DAMAGE_HOOD = 0x23,
	CARSLOTID_DAMAGE_SIDEMIRROR_LEFT = 0x24,
	CARSLOTID_DAMAGE_SIDEMIRROR_RIGHT = 0x25,
	CARSLOTID_DAMAGE_TRUNK = 0x26,
	CARSLOTID_DAMAGE_WIDEBODY = 0x27,
	CARSLOTID_DAMAGE_WIDEBODY_BUMPER_FRONT = 0x28,
	CARSLOTID_DAMAGE_WIDEBODY_BUMPER_REAR = 0x29,
	CARSLOTID_DAMAGE_WIDEBODY_DOOR_LEFT = 0x2A,
	CARSLOTID_DAMAGE_WIDEBODY_DOOR_REAR_LEFT = 0x2B,
	CARSLOTID_DAMAGE_WIDEBODY_DOOR_REAR_RIGHT = 0x2C,
	CARSLOTID_DAMAGE_WIDEBODY_DOOR_RIGHT = 0x2D,
	CARSLOTID_DAMAGE_WIDEBODY_FENDER_FRONT_LEFT = 0x2E,
	CARSLOTID_DAMAGE_WIDEBODY_FENDER_FRONT_RIGHT = 0x2F,
	CARSLOTID_DAMAGE_WINDOW_FRONT = 0x30,
	CARSLOTID_DAMAGE_WINDOW_FRONT_LEFT = 0x31,
	CARSLOTID_DAMAGE_WINDOW_FRONT_RIGHT = 0x32,
	CARSLOTID_DAMAGE_WINDOW_REAR = 0x33,
	CARSLOTID_DAMAGE_WINDOW_REAR_LEFT = 0x34,
	CARSLOTID_DAMAGE_WINDOW_REAR_RIGHT = 0x35,
	CARSLOTID_DAMAGE0_FRONT = 0x36,
	CARSLOTID_DAMAGE0_FRONTLEFT = 0x37,
	CARSLOTID_DAMAGE0_FRONTRIGHT = 0x38,
	CARSLOTID_DAMAGE0_REAR = 0x39,
	CARSLOTID_DAMAGE0_REARLEFT = 0x3A,
	CARSLOTID_DAMAGE0_REARRIGHT = 0x3B,
	CARSLOTID_DECAL_FRONT_WINDOW = 0x3C,
	CARSLOTID_DECAL_REAR_WINDOW = 0x3D,
	CARSLOTID_DOOR_LEFT = 0x3E,
	CARSLOTID_DOOR_REAR_LEFT = 0x3F,
	CARSLOTID_DOOR_REAR_RIGHT = 0x40,
	CARSLOTID_DOOR_RIGHT = 0x41,
	CARSLOTID_DOORHANDLE_FRONT_LEFT = 0x42,
	CARSLOTID_DOORHANDLE_FRONT_RIGHT = 0x43,
	CARSLOTID_DOORHANDLE_REAR_LEFT = 0x44,
	CARSLOTID_DOORHANDLE_REAR_RIGHT = 0x45,
	CARSLOTID_DRIVER = 0x46,
	CARSLOTID_ENGINE = 0x47,
	CARSLOTID_EXHAUST = 0x48,
	CARSLOTID_FENDER_FRONT_LEFT = 0x49,
	CARSLOTID_FENDER_FRONT_RIGHT = 0x4A,
	CARSLOTID_HEADLIGHT_GLASS_LEFT = 0x4B,
	CARSLOTID_HEADLIGHT_GLASS_RIGHT = 0x4C,
	CARSLOTID_HEADLIGHT_LEFT = 0x4D,
	CARSLOTID_HEADLIGHT_RIGHT = 0x4E,
	CARSLOTID_HOOD = 0x4F,
	CARSLOTID_LICENSE_PLATE = 0x50,
	CARSLOTID_ROLL_CAGE = 0x51,
	CARSLOTID_ROOF = 0x52,
	CARSLOTID_ROOF_INSIDE = 0x53,
	CARSLOTID_ROOFSCOOP = 0x54,
	CARSLOTID_SEAT_LEFT = 0x55,
	CARSLOTID_SEAT_RIGHT = 0x56,
	CARSLOTID_SIDE_MIRROR_LEFT = 0x57,
	CARSLOTID_SIDE_MIRROR_RIGHT = 0x58,
	CARSLOTID_SKIRT_LEFT = 0x59,
	CARSLOTID_SKIRT_RIGHT = 0x5A,
	CARSLOTID_SPOILER = 0x5B,
	CARSLOTID_STEERINGWHEEL = 0x5C,
	CARSLOTID_TRUNK = 0x5D,
	CARSLOTID_UNIVERSAL_SPOILER_BASE = 0x5E,
	CARSLOTID_WHEEL_FRONT = 0x5F,
	CARSLOTID_WHEEL_REAR = 0x60,
	CARSLOTID_WINDOW_FRONT = 0x61,
	CARSLOTID_WINDOW_FRONT_LEFT = 0x62,
	CARSLOTID_WINDOW_FRONT_RIGHT = 0x63,
	CARSLOTID_WINDOW_REAR = 0x64,
	CARSLOTID_WINDOW_REAR_LEFT = 0x65,
	CARSLOTID_WINDOW_REAR_RIGHT = 0x66,
	CARSLOTID_WINDTUNNEL_TYPE1 = 0x67,
	CARSLOTID_WINDTUNNEL_TYPE10 = 0x68,
	CARSLOTID_WINDTUNNEL_TYPE2 = 0x69,
	CARSLOTID_WINDTUNNEL_TYPE3 = 0x6A,
	CARSLOTID_WINDTUNNEL_TYPE4 = 0x6B,
	CARSLOTID_WINDTUNNEL_TYPE5 = 0x6C,
	CARSLOTID_WINDTUNNEL_TYPE6 = 0x6D,
	CARSLOTID_WINDTUNNEL_TYPE7 = 0x6E,
	CARSLOTID_WINDTUNNEL_TYPE8 = 0x6F,
	CARSLOTID_WINDTUNNEL_TYPE9 = 0x70,
	CARSLOTID_BODY_PAINT = 0x71,
	CARSLOTID_BODY_PAINT_GROUP = 0x72,
	CARSLOTID_BODY_PAINT_SWATCH = 0x73,
	CARSLOTID_BUMPER_FRONT_PAINT = 0x74,
	CARSLOTID_BUMPER_FRONT_PAINT_GROUP = 0x75,
	CARSLOTID_BUMPER_FRONT_PAINT_SWATCH = 0x76,
	CARSLOTID_BUMPER_REAR_PAINT = 0x77,
	CARSLOTID_BUMPER_REAR_PAINT_GROUP = 0x78,
	CARSLOTID_BUMPER_REAR_PAINT_SWATCH = 0x79,
	CARSLOTID_CHASSIS = 0x7A,
	CARSLOTID_DRIVETRAIN_PACKAGE = 0x7B,
	CARSLOTID_ENGINE_PACKAGE = 0x7C,
	CARSLOTID_FORCED_INDUCTION_PACKAGE = 0x7D,
	CARSLOTID_HOOD_PAINT = 0x7E,
	CARSLOTID_HOOD_PAINT_GROUP = 0x7F,
	CARSLOTID_HOOD_PAINT_SWATCH = 0x80,
	CARSLOTID_INTERIOR = 0x81,
	CARSLOTID_LIVERY = 0x82,
	CARSLOTID_NITROUS_PACKAGE = 0x83,
	CARSLOTID_ROLLCAGE_PAINT = 0x84,
	CARSLOTID_ROLLCAGE_PAINT_GROUP = 0x85,
	CARSLOTID_ROLLCAGE_PAINT_SWATCH = 0x86,
	CARSLOTID_ROOF_SCOOP_PAINT = 0x87,
	CARSLOTID_ROOF_SCOOP_PAINT_GROUP = 0x88,
	CARSLOTID_ROOF_SCOOP_PAINT_SWATCH = 0x89,
	CARSLOTID_SIDE_MIRROR_PAINT = 0x8A,
	CARSLOTID_SIDE_MIRROR_PAINT_GROUP = 0x8B,
	CARSLOTID_SIDE_MIRROR_PAINT_SWATCH = 0x8C,
	CARSLOTID_SKIRT_PAINT = 0x8D,
	CARSLOTID_SKIRT_PAINT_GROUP = 0x8E,
	CARSLOTID_SKIRT_PAINT_SWATCH = 0x8F,
	CARSLOTID_SPOILER_PAINT = 0x90,
	CARSLOTID_SPOILER_PAINT_GROUP = 0x91,
	CARSLOTID_SPOILER_PAINT_SWATCH = 0x92,
	CARSLOTID_SUSPENSION_PACKAGE = 0x93,
	CARSLOTID_TIRE_FRONT = 0x94,
	CARSLOTID_TIRE_PACKAGE = 0x95,
	CARSLOTID_TIRE_REAR = 0x96,
	CARSLOTID_VECTORVINYL = 0x97,
	CARSLOTID_VINYL_PAINT = 0x98,
	CARSLOTID_WHEEL_PAINT = 0x99,
	CARSLOTID_WHEEL_PAINT_GROUP = 0x9A,
	CARSLOTID_WHEEL_PAINT_SWATCH = 0x9B,
	CARSLOTID_WHEEL_SPOKE_FRONT_PAINT = 0x9C,
	CARSLOTID_WHEEL_SPOKE_FRONT_PAINT_GROUP = 0x9D,
	CARSLOTID_WHEEL_SPOKE_FRONT_PAINT_SWATCH = 0x9E,
	CARSLOTID_WHEEL_SPOKE_REAR_PAINT = 0x9F,
	CARSLOTID_WHEEL_SPOKE_REAR_PAINT_GROUP = 0xA0,
	CARSLOTID_WHEEL_SPOKE_REAR_PAINT_SWATCH = 0xA1,
	CARSLOTID_WINDOW_TINT = 0xA2,
	CARSLOTID_WINDOW_TINT_GROUP = 0xA3,
	CARSLOTID_WINDOW_TINT_SWATCH = 0xA4,
	CARSLOTID_NUM = 0xA5,
	CARSLOTID_MODEL_FIRST = 0x0,
	CARSLOTID_MODEL_LAST = 0x70,
	CARSLOTID_MODEL_NUM = 0x71,
	CARSLOTID_FIRST_NONRENDER = 0x71,
	CARSLOTID_LAST_NONRENDER = 0xA4,
	CARSLOTID_NONRENDER_NUM = 0x34,
	CARSLOTID_DAMAGE_MODEL_FIRST = 0x16,
	CARSLOTID_DAMAGE_MODEL_LAST = 0x35,
	CARSLOTID_DAMAGE_MODEL_NUM = 0x20,
	CARSLOTID_DAMAGE_PLAYER_MODEL_FIRST = 0x36,
	CARSLOTID_DAMAGE_PLAYER_MODEL_LAST = 0x3B,
	CARSLOTID_DAMAGE_PLAYER_MODEL_NUM = 0x6,
	CARSLOTID_DECAL_MODEL_FIRST = 0x3C,
	CARSLOTID_DECAL_MODEL_LAST = 0x3D,
	CARSLOTID_DECAL_MODEL_NUM = 0x2,
};

enum KIT_TYPE {
	KIT_TYPE_BASE = 0,
	KIT_TYPE_STOCK = 1,
	KIT_TYPE_AUTOSCULPT = 2,
	KIT_TYPE_WIDEBODY = 3,
	NUM_KIT_TYPE = 4,
};

struct PackedVinylColor {
	int16_t huePart;
	uint8_t saturation;
	uint8_t brightness;
};

class PackedVinylLayer {
public:
	int16_t vinylPart;
	VinylSystem::VinylTransformPacked transform;
	PackedVinylColor colors[4];
};

class PackedDecalLayer {
public:
	int16_t decalPart;
	VinylSystem::VinylTransformPacked transform;
	PackedVinylColor color;
};

class RideInfo;
class VehicleCustomizations {
public:
	int16_t GUID[5];
	unsigned int creatorId;
	char creatorName[32];
	unsigned int shareNumber;
	int16_t InstalledParts[165];
	uint8_t customPaintsValid[12];
	CarPaintPartRecordPacked customPaints[12];
	uint8_t partBaseMaterials[12];
	BluePrintType bluePrintType;
	KIT_TYPE kitType;
	unsigned int kitNum;
	float RideHeight;
	PackedVinylLayer VinylLayers[20];
	int VinylMirrorBits;
	int NumVinylLayers;
	PackedDecalLayer DecalLayers[20];
	int DecalMirrorBits;
	int NumDecalLayers;
	int LiveryID;
	uint8_t MorphValues[41][11];
	float PhysicsTuning[32];
	int Type;

	static inline auto GetInstalledPart = (bool(__thiscall*)(VehicleCustomizations*, CAR_SLOT_ID, int, DBCarPart*))0x782F70;
};
static_assert(sizeof(VehicleCustomizations) == 0x7B4);